BASE=0
i=1
KSPROJECT=ksProject.sh
SEP=_

BASEDATA=tmp/data
BASECACHE=tmp/cache
BASELOG=tmp/log
BASEDB=db/db
BASETXT=tmp/txt
BASERSS=tmp/rss
ENDRSS=.rss

DATA="$BASEDATA$SEP$USER$SEP"
CACHE="$BASECACHE$SEP$USER$SEP"
WGETLOG="$BASELOG$SEP$USER"
DBFILE="$BASEDB$SEP$USER"
TXTFILE="$BASETXT$SEP$USER"
RSSFILE="$BASERSS$SEP$USER$ENDRSS"
